---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      # - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args:
        - --unsafe
      - id: debug-statements
      - id: destroyed-symlinks
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch
      - id: pretty-format-json
        args:
        - --autofix
        - --indent
        - "2"
        exclude: "package.*\\.json"
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args:
        - --markdown-linebreak-ext=md
        exclude: ".*\\.patch"
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.6
    hooks:
      - id: uv-lock
      - id: uv-export
        args:
        - --frozen
        - --output-file=requirements.txt
        - --no-hashes
        - --no-emit-project
      - id: uv-export
        args:
        - --frozen
        - --output-file=requirements-dev.txt
        - --no-hashes
        - --all-extras
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.3
    hooks:
      - id: cspell
        files: |
            (?x)^(
                Makefile|
                docs/.*|
                mkdocs.yml
                samples/.*|
                src/.*|
                tests/.*
            )$
        exclude: |
            (?x)^(
                .*\.css|
                .*\.scss|
                docs/examples/admonitions.md|
                docs/examples/annotations.md|
                docs/examples/content-tabs.md|
                docs/examples/footnotes.md|
                docs/examples/images.md|
                docs/examples/lists.md
            )$
